name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup System
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
    - uses: rhysd/action-setup-vim@v1
      with:
        version: v8.1.0123
    - name: Run tests
      run: ./run.sh
